projetoFinal/config/routes.rb
Rails.application.routes.draw do
  get 'posts/welcome'

  get 'abouts/about'

  root 'posts#index'
  resources :posts

  resources :artista
  devise_for :usuarios

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

projetoFinal/app/models/about.rb
class About < ApplicationRecord
end

projetoFinal/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

projetoFinal/app/models/post.rb
class Post < ApplicationRecord
	
	
	has_attached_file :image, :styles => {:medium => "500*500"}
	validates_attachment_presence :image
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	has_attached_file :music
	validates_attachment_presence :music
	validates_attachment_content_type :music, :content_type => /.*/

end

projetoFinal/app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

projetoFinal/app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def about
  end
end

projetoFinal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

projetoFinal/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def welcome
  end
   def new
  	@post = Post.new
  end

  def index
  	@posts = Post.all.order("created_at DESC")
  end

  def show
  	@post = Post.find(params[:id])

  end

  def create
  	@post = Post.new(permit_post)
	  	if @post.save
	  		flash[:success] = "Postagem feita com sucesso!"
	  		redirect_to post_path(@post)
	  	else
	  		flash[:error] = @post.errors.full_messages
	  		redirect_to new_post_path
	  	end
  	end
  private 
  	def permit_post
  		params.require(:post).permit(:image,:music,:descricao)
  	end
end

projetoFinal/app/helpers/abouts_helper.rb
module AboutsHelper
end

projetoFinal/app/helpers/application_helper.rb
module ApplicationHelper
end

projetoFinal/app/helpers/postagens_helper.rb
module PostagensHelper
end

projetoFinal/app/helpers/posts_helper.rb
module PostsHelper
end

projetoFinal/app/views/abouts/about.html.erb
<h1>Sobre o husky</h1>

<article>
 <br>
 <br>
 <font size="6" face="verdana">
  A ideia do site é baseada no cymbal, um aplicativo para plataformas móveis disponível para Android e iOS.
  <br>
  <br>
  <font size="4">
  Esse projeto não tem fins comerciais,tendo apenas objetivos educacionais e servindo de um exercício prático na disciplina de Orientação a Objetos
  </font>
  <br>
  
  </font>
</article>

projetoFinal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>husky</title>
  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= csrf_meta_tags %>
  <style>
  #Image{     
     
     border-width: 10px;  border-radius: 10px; border-color:#ffffff;   border-style: solid; 
    }
    

    </style>
  </head>
 
  <body>
    
  
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <%= link_to "husky", root_url, class: "navbar-brand"%>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to "Sobre", abouts_about_path %>
                    </li>
                    <li>
                        
                        <%= link_to "Nova postagem", new_post_path %>
                    </li>
                        <%- if current_usuario %>
                        <li>
                        <%= link_to "Logout",destroy_usuario_session_path, method: :delete, data: {confirm: "Você tem certeza?"} %>
                        </li>
                        <% else %>
                    <li>
                        <%= link_to "Login",new_usuario_session_path %>
                    </li>
                    <li>
                        <%= link_to "Registrar-se", new_usuario_registration_path %>
                    </li>
                    <% end%>
                    <li>
                        
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12 text-center">
                <% flash.each do |a , b| %>
                    <div class = "alert alert-success"> <%= b %> </div>
                <%end%>
            	<%= yield%>	

            </div>
        </div>
        <!-- /.row -->
        </div>
        <!-- /.container -->
        <style>body{padding-top:70px;
            background-color: #f5f5ef;}</style>
        </body>
</html>

projetoFinal/app/views/posts/index.html.erb
<% @posts.reverse.each do |x| %>
	<img  id="Image"
		<%=image_tag x.image.url(:medium)%>
		
		<br>
		<br>
		
		<%= audio_tag x.music.url,autoplay: false, controls: true, preload: true%></td>
		<br>

		<%= x.descricao %>
		<br>
		<br>
<% end%>

projetoFinal/app/views/posts/new.html.erb
<h1>Nova Postagem</h1>


<%= form_for @post,html: { multipart: true } do |f| %>
	
	
<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <div class="input-group">
        	<br>
            <%= f.label :image,"Imagem" %>
            <br>
			<%= f.file_field :image  %>
			<br>
			<br>
			<br>
			<%= f.label :music,"Música" %>
			<br>
			<%= f.file_field :music%>
			<br>
			<br>
			<br>
			<%= f.label :descricao,"Descrição"%>
			<br>
			<%= f.text_area :descricao%>
			<br>
			<br>
			<%= f.submit "Postar" %>
            
    </div><!-- /.col-lg-4 -->
</div><!-- /.row -->


<% end %>

projetoFinal/app/views/posts/show.html.erb
<div class="white">
	<%= image_tag(@post.image.url(:medium)) %>
	<br>
	<%= audio_tag(@post.music_file_name) %>
	<br>
	<br>
	<%= @post.descricao %>
</div>

projetoFinal/app/views/posts/welcome.html.erb
<h1>Bem-vindo ao husky!</h1>

<article>
 <br>
 <br>
 <font size="6" face="verdana">
  husky é um site para o upload de arquivos de música e imagens baseado em ruby on rails.
  <br>
  
  </font>
</article>